### PR TITLE
Initial upload from local source

### PR DESCRIPTION
**Pull request by davehocking**
Hi there, here's the local source I've been working on, ready for review. It looks like I may have worked on an older version of the style.ps1 file, so there are some diffs there that I don't recognise.

### CODE REVIEW

**Comment by Sneddo** [comment]
Yeah, there's a bit of work to clean this up.

Currently, based on a quick skim through:
- The HTML Config GUI won't work (probably)
- Some of the changes for PowerCLI Core have been reverted

We can probably just replace vCheck.ps1 and vCheckUtils.ps1 with a copy from the dev branch of vCheck-vSphere to cover some of this.

I'll merge it anyway, and we can work on fixing these.

**Comment by davehocking** [comment]
I tinkered with vCheck.ps1 to auto-load PowerCLI modules, that can easily be removed, the Style changes can be re-done easily enough, if it makes it easier than trying to merge my stuff in?

**Comment by Sneddo** [comment]
I don't think it will be too much effort, just little things like you mentioned. 

I do think minimising changes to vCheck.ps1 is good, so we can easily merge updates from the other repos more easily. Otherwise it's just a matter of testing and squishing any bugs :)

**Comment by davehocking** [comment]
Agreed. Bedtime now, catch up with this tomorrow :)

**Pull request merged**
