### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by davehocking**
Hi @vScripter am I doing things the right way with respect to Git? - I grabbed a fresh copy of the repo, then created a new local branch from "develop", staged my file and committed/pushed to remote develop. I guess we just queue up a chunk of changes and then do a merge with master at some point in the future?

### CODE REVIEW

**Comment by vScripter** [comment]
Yep, that's the general idea; always push changes to the `develop` branch and then once enough updates are made to warrant a new version, I 'create a release', which merges `develop` into master and then rebases `develop` from master so that the new `develop` branch is a mirror from `master` including the tags for the new version. That may have sounded pretty confusing, but it's the basics of using the Git-Flow methodology. The easy way to remember is always push to `develop`.

**Comment by davehocking** [comment]
That makes sense, sorry my contribution slowed right down, am currently trying to get a new job, so lots of time being taken over interview/presentation prep right now!

**Comment by davehocking** [comment]
I'm seeing some oddness around the file formats - It's reporting as binary?? - seems to open OK but it's screwing up the side-by-side diff. Any idea what I've done wrong/how to fix @vScripter ?

**Comment by vScripter** [comment]
Make sure your editor is set to use `UTF-8` for file encoding, as the default; it's probably set to `UTF-16`. For existing files, you'll need to re-save with `UTF-8`. Some other settings you might want to set:
* Trim white space at the end of each line on save
* Use LF line endings vs. CRLF _(not critical but it keeps file diffs consistent, in my experience; only downside is when you open the file in Windows with Apps like Notepad, it basically becomes one long line of code)_

What editor are you using?

**Pull request merged**
