### PR TITLE
Readme update

### PR DESCRIPTION
**Pull request by davehocking**
OK, suggested changes made from previous PR

### CODE REVIEW

**Comment by vScripter** [comment]
- README looks good.

- For the installation of the PowerNSX module, when checking for the module, instead of:
```
# Check for PowerNSX presence, and link to installer if missing
import-module PowerNSX
$commands = Get-Command -Module PowerNSX
```

It might be better suited to check for the module, even if it's not loaded, and then attempt to install. This example shows how you could accomplish that (sorry for format changes; my IDE auto-formats on paste)
```
# Check for PowerNSX presence (version 2.x), and link to installer if missing
$nsxModuleCheck = $null
$nsxModuleCheck = Get-Module -ListAvailable | Where-Object { $psitem.Name -eq 'PowerNSX' -and $psitem.version -like '2.*' }

if (!$nsxModuleCheck) {

```

**Comment by davehocking** [comment]
ahh yes, mine is a little crude by comparison! - will update shortly

**Comment by davehocking** [comment]
ok, updates made

**Comment by vScripter** [comment]
@davehocking PR closed and I removed the `readme-update` branch. 👍

**Comment by davehocking** [comment]
What happens next? - How does this change make it to "master" ?

**Comment by vScripter** [comment]
@davehocking I created a release branch and then merged into master. Typically, we will work in the `develop` branch until there are enough changes made to warrant a release (stable/fully functional build). Modifying a README file is really more of a 'Hotfix', and typically is just pulled and pushed to `master` and `develop`. I'm using the __Git-Flow__ methodology: a good writeup can be found here, if you want to ready more about it: http://nvie.com/posts/a-successful-git-branching-model/

**Comment by davehocking** [comment]
thanks, reading.. :)

**Pull request merged**
